apiVersion: v1
kind: Service
metadata:
  name: react-chart
  namespace: crd
  labels:
    app: test
spec:
  selector:
    app: react-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      protocol: TCP
      targetPort: 9113
